sudo: required

services:
  - docker

language: bash

before_script:
  - git clone https://github.com/lukebond/microscanner-wrapper.git
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - docker build -t jrromb/openvpn .
  - microscanner-wrapper/scan.sh jrromb/openvpn:latest
  - fossa init
  - fossa analyze
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jrromb/openvpn:latest
  - docker logout

after_success:
  - curl -d "" https://hooks.microbadger.com/images/jrromb/rasp-plex/$MICROBADGER

notifications:
  webhooks: https://app.fossa.io/hooks/travisci