dist: bionic
services:
- docker
language: bash
env:
  - CONTAINER=jrromb/rasp-plex      DIR=rasp-plex       QEMU=1
  - CONTAINER=jrromb/http-test      DIR=http-test
  - CONTAINER=jrromb/openvpn-as     DIR=openvpn-as
  - CONTAINER=jrromb/tautulli-rpi   DIR=tautulli-rpi    QEMU=1     ARCH=arm   SCRIPT=build.sh

script: 
  - echo "BUILDING $CONTAINER"
  - | 
    cd $DIR
    if [ ! -z "$SCRIPT" ] ; then
      ./$SCRIPT
    else
      [ -z "$QEMU" ] && docker run --rm --privileged multiarch/qemu-user-static:register --reset
      docker build -t $CONTAINER:latest .
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $CONTAINER:latest
      docker logout
    fi
  - |
    echo "updating DockerHub description"
    pwd
    [ -f ./README.md ] && ../update_dockerhub_desc.sh || echo "NO ./README.md FOUND"

