dist: bionic
sudo: required
services:
- docker
language: bash
env:
  global:
  - TRIVY_CACHE="/tmp/trivy_cache"
  - IMG_NAME="jrromb/tautulli-rpi"
  - secure: JJbnN/00JsP35wWWE8QlbsMOn+belvRYwAqTMXuhlrNilQkssoRzzJADP74KcTJX6ue4wlZ4ffoapty2Z3F9aeylX2GtEk/N+wRTTcE0/BGWh8sPZaNHimorzllkpUf/yZqttI2hcJbE9B88wSQFZnnv6Eua1Y3oYYBT0fJugiSiVXE7qMrWbdPwQ6dpH+EGYjPfRAOCNspjudBwcgQwJx47C5Febixkjn6+oDiTjOZXQtkjX12E17HjgFGtmlNlo0UA8vXkgQIgmuYvAu9SqpiqsTnxH1Lhy6M8Jh0QqlHeNgDjeDylFKR+coNKCKVGgr/EJ/1NJCZJFUada8wDit6azJypbfOutZZal8ibltZ9ImHW8Ih9WWu+nELxWGfnbuW6/ImTceTz7/tPNNRCQVqQ1U9ABjj3Hbq6fvrQKY5WYrfg1GpmR6pdwpT1KJtIeLyTifLLskBF9n5lUmpue0mHbkbaV9MMNIo+nPr4scqmxQoO8k/Kz9t6+y1B4lP33KxtKkx+IvGpqKZ9zzP9DuzvehDBZRIJBBIInGB9hQlln0+HOwoeGFf9Kk3wjI3V+AQNVtJq5wC5YfpgfiY6o+8nyy0EeycgJ4B9jjqVgkiyxDzd9oOepwXK0fmHgZN21uzZeOxSUxAjVp2KhawN4B7sa7GBsitRsTNs0UPUZak=
  - secure: nABEt13ttemVRuJyRXLlQkFvcOu3WvmBvuvewdy4V9USocDmjKzv8qc75Z7I6KOwpXgGeBcrF7MhAb5KBMRkNg3OsZpNZbmBEe7vAgRUQo2K13lB26AEBXEgjde0BczbcKweO32cmtTcxEBTVKTvP3LqNXF7LFlT2aiju6RiOvCEALrJCL2pp7zVBKkQd6AtI6jS7qBir1H5UQFcK/cBd+r2nXvOUdqNE3l1H9AAi2WxJo4a3DtO24pJBi21KofJf+xzmC71XrIjwmfYBwcXKccptXbJ20Z4skgmeCwpny4W6bTjjGOXAOUDY7Cp1eBlKysTySk3/D5jUmVa51exEC+hM3eX1iHaqnigGAn9DHO1Mnc4GoO0BeKBD9nSiADRkK/C9Fey+lNwd49sGT8AIClVRjkE5qrM5u1E/DEJRhPShdPltCOTP3ydmbbILPhRjzW/77WkAdg/OGivRE4aWBpk2TMqabo6UPkiEbNzqTvQjmbPH0uEoEKICT6B0vgFxxg1Jr9eAxE04HO6BdiIhgOFmaeVjGPKpLxMfUNfDa9i2TkqH/H1NBQzI37UOfj327WIHq7I2ISy9tw2eRE33yxoa1wPIpX30/q+iAqDjhGSDgvhAAeEdQrIe34uDyyQ0ZyHScWpPcjmkC2OId6ttypL6dnrQ77UmHoESp0l/lI=
  - secure: DcOZeOAjuQNzThMoBCvswpTKZGf0Ksp2rf3zE2AwynrMhuk1ZED7bM1d8UlO/gXDB2JlBKxZnlSQZ5D65xoDLLAgahfu3DFHXWRdXfgJK/LC40riRi5VB+E6/q+Hmhza3nomZKgDABJwJlP1dxmDw5hirvw+KJmPHIDxedwGAMQEqAWzYlGClDaVj77AwF5Ywr2lko6dC2YBHH4tQ3OKjI4xUrDPwAf7aXNOb8MntlvpDSvzqhAaW6WMgqoH7sW43G7YUBmuV1LuPLSxGAcgA1wBTxC5VjAWhcQNHR5LssPbLnKL1oWJZcstHv3ZYzsPhdc7pl6xr6hWJna7aWyWwjq6T3kLH7lazGecg1W0J4pPLyAJi3ykXSKUNuRlKONGgu+/66rSnK7vdPWzg0ftnP/68W6Kg3LrioW5kU2vMjkqL5zrcJ2ZoSQQa0R4uG0ggMt+Zma9bpepU9QVhfmsU60Fry4fPYEJ8wz27OnXYEVYLHJ5BYpdbkc4JSWl/TDzLYE16aTZ0Ydwwa8o7lg5q6rM6QaAC+hNIKzx5HLE02jRpXSXY4MFbS4EQzXU/PBZ4LeJJKJH7Se6N4/un0FYTseTXod5sUH8urfIEsM7rlUppa5OdHCnbssLAQTd6bzt8D9i4Lo7itIvoUOcDzEiRVO9JoyJbgSse3aWwt098cg=
jobs:
  include:
  - script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build -t $IMG_NAME .
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - docker push $IMG_NAME
    - docker logout
    - curl -X POST https://hooks.microbadger.com/images/jrromb/rasp-plex/${MICROBADGER_TOKEN}
