dist: bionic
sudo: required

services:
  - docker

language: bash

env:
  global:
    TRIVY_CACHE="/tmp/trivy_cache"
    IMG_NAME="jrromb/rasp-plex"

jobs:
  include:
    - script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build -t $IMG_NAME .
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      - docker push $IMG_NAME
      - docker logout
      - docker run --rm -v $TRIVY_CACHE:/root/.cache/ aquasec/trivy --exit-code 0  --no-progress -f json  $IMG_NAME

    
    


