sudo: required

services:
  - docker

language: bash

env:
  global:
    - secure: "l1L+XfWTToZtKxjdd2Lv6b5jNdyshbKQJ8C2fIttAO/o56+XuFTfzwEwYe4J4QXWTc1AMeyWAQiP9LQuZfadvOpDakLjJqA0t0rqBJscgcwAokP88Wh5ZMsUe0xFXeQ9sPR0F+xDNmDMUvxx4U1mzpE/T47hy5rjS/i3X3oaLgd9Uyem7CCYMbTr5OQkQumkWwY1Dqr9mKKl/sDBjKqndoumZoecZnZ6trbB9Vl/mVUtkD6lvUfN9wWznu9MWAI7wUW1Q1RtMtm0FChsesP8zxTOm5DceSTv86W7JWvWBoIItoFThKhOpj5t5j41tejviGQypX1ZDI2SCaD//4aiNK9Su9UF4Dvu/my+ti2/96e8FZwhrYoPIyrio1lhpHNWsQxJqlwWcrMhfd64qehQWVm+No7i15J++OZINL+BQTEhVSA2kA1uwfpoEu8h3TPzElHvBZKXkM9PTVEPDKN9chakEe/tjie6tpBYOiLnREnSi0o43vKdR1iMom8/OrFsu22C6gpOanf5CTAISRj2kSu50fTHZTik5TKSJ3wmfIZZVjKYtChZ4ulyPcPrftixEfM+rqIkXZdLc0ZhIkoMcWUBs7itgw8yeLXvkI4AcigiKaewVNni0VA/0d4CAx50LNhLrTG4jKt611SikVh5791BL+lwrl9mSM+4T/ayAg8="
    - secure: "QGSYuILk9nexmxA92mf2Qg1kewRx1YnBGgMY0Nus8MyiOJrphNR4zd91iVd/qFQcjs121dBEkNghrHRSItXgksw5QdnNbAE+Mfb2l6/tMfEHQv+b9a4Exg+qfbqS5w3X7IShPvzgrVZ6HRaATEfxegj4AdJg7pBiDofQm1L5sv/u+WLn36L7U7FuXUMI/aXrMNKqnjhD34lTVSpjxnEPsKCaTNdsWMqpzZL52/fjf5Fz3hknGY7eYua5uMq/q0B9wm6sXgiAsKU9aNHDhV2Lzq7VnETP4piAqpE7mYx6mJMQEvZGfHKH/w1XO2TeJgHvI7ELDluiQX4BS6KMFqdhy7ON8EWJ1Njo7EfkvYSX1G/d6ShKpzPx8ilFDl6Ca0uk0kl/9vtQBFGni0vjyCaKIQN1JC2yTI/FRpN+yd12QGkjX6Mm7WivxzALtZ68Mv52g5UTdimLzbv6/yRNJnO96Goxb5KYq6EymV8MN1uxPFNLShA+wPTdZU3p2WsJt2v2wp+crh4R94P3M6bRLzI5VZgp0QjccIe8aT4ONjubG8RxAj0eQCEDBLOA6+NexCBYvm6ydNw2PPRUhCRACtQ9vavJRGCQYt+IKWQfU3PRNUTPprmQiwf50W1+0Iu0coNEYoAMFLY7KWMeImz1Iw4O36j/VwUSnyVMSR7ujyGXszg="
    - secure: "rwj0g90su0wDLGGTQwS637eKW5LaxK0wNeLO2u3/hMb/hvsDlFzA9PyyCh+9oj4UvKdSrORlejC2nvEwbOrcu37bwFi9FkIaN9TaGkcppGBewvwBhPUSGn4KtsD5w+iAuLHc7SPPK9Gb6cX0J34ygoAqAnZHtE3Dt/yzCfPQVr7oDnmRzYYG+q9S9fltTTuj9y2NHRdHki/vOxL/RaJNBIBaNotYvJjwoOO1rKbkRYEZO4bJkso05uBlJ2A8w9qAnvES3EIQVHnt/0kNntfdsxKoyMMN3WVsWblqvwc0vA9OKlvFU0S2aw75YhNACrVdQWKyttGpvqq+PbgYXMN16GMewoJBrfiupHfMMObM0jmlI8GR++aNZehKh1ENAxgGizeDHq8doBCUn141H4VCHfMVoLekXANMgFT5t3pUkyO7IH9CYFOB2NM39t+Obnc7IHzOPWjESEBxQ/SM/nbosXmUN6k97/TZcz439bpzVAE5Zwqp677eH2sbxHjTq7UeroIIpwntoLtKMhYjW8Lb2YPJ+84O0qBqS0nSUldRpoOMUgsUAB46GeV6uM7gBu33G8rEO+GZQW+Ipyc5SXLsI266kAlRKRHKHIJ1yitiAv9WDcoRRPftKuoZu3Cv5JoI0ih9SvNbLgkztR5+jaCQTL/AZNGetzb5AhT8t4Hv94I="

jobs:
  include:
    - stage: build
      script:
        - cd openvpn-as
        - docker build -t jrromb/openvpn .
    # - stage: validate
    #   script: 
    #     - git clone https://github.com/lukebond/microscanner-wrapper.gitdocker
    - stage: deploy
      script: 
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push jrromb/openvpn:latest
        - docker logout
      after_success:
      - curl -d "" https://hooks.microbadger.com/images/jrromb/openvpn/$MICROBADGER
