vpn-proxy:
  image: jrromb/vpn-proxy
  privileged: true
  restart: always
  container_name: vpn-proxy
  environment:
    VPN_USER: openvpn
    VPN_PASS: changeme
  ports:
    - 1080:1080
  volumes:
    - /Users/junicarl/Downloads/google.ovpn:/client.ovpn