#!/usr/bin/with-contenv sh

# creating openvpn credentials file for a headless start
echo -e "${VPN_USER}\n${VPN_PASS}" > ${VPN_CRED}


exec s6-setuidgid root openvpn \
    --config /client.ovpn \
    --script-security 2 \
    --up /etc/openvpn/up.sh \
    --down /etc/openvpn/down.sh
    --auth-user-pass ${VPN_CRED}

#     \
#    --log-append /var/log/openvpn.log \
#    --daemon openvpn



script-security 2
up /etc/openvpn/up.sh
down /etc/openvpn/down.sh